// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebsiteBanHang.Areas.Admin.Data;

#nullable disable

namespace WebsiteBanHang.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WebsiteBanHang.Areas.Admin.Models.BrandModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("MaHang")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("NgaySanXuat")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenHang")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("XuatXu")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Brand");
                });

            modelBuilder.Entity("WebsiteBanHang.Areas.Admin.Models.CategoryModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("MaLoai")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("WebsiteBanHang.Areas.Admin.Models.PermissionRoleModel", b =>
                {
                    b.Property<int>("Permission_ID")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("Role_ID")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.HasKey("Permission_ID", "Role_ID");

                    b.HasIndex("Role_ID");

                    b.ToTable("PermissionRole");
                });

            modelBuilder.Entity("WebsiteBanHang.Areas.Admin.Models.PermissionsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Access")
                        .HasColumnType("bit");

                    b.Property<bool>("Add")
                        .HasColumnType("bit");

                    b.Property<bool>("Edit")
                        .HasColumnType("bit");

                    b.Property<string>("FunctionName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Remote")
                        .HasColumnType("bit");

                    b.Property<bool>("Show")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("WebsiteBanHang.Areas.Admin.Models.ProductModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Gia")
                        .HasColumnType("int");

                    b.Property<int?>("HangId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("LoaiId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("MaSanPham")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ThongTinSanPham")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("HangId");

                    b.HasIndex("LoaiId");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("WebsiteBanHang.Areas.Admin.Models.RoleModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("WebsiteBanHang.Areas.Admin.Models.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MatKhau")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("WebsiteBanHang.Areas.Admin.Models.UserRoleModel", b =>
                {
                    b.Property<int>("User_ID")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("Role_ID")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.HasKey("User_ID", "Role_ID");

                    b.HasIndex("Role_ID");

                    b.ToTable("UserRole");
                });

            modelBuilder.Entity("WebsiteBanHang.Areas.Admin.Models.Users_Details", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("SoDienThoai")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.ToTable("Users_Details");
                });

            modelBuilder.Entity("WebsiteBanHang.Areas.Admin.Models.PermissionRoleModel", b =>
                {
                    b.HasOne("WebsiteBanHang.Areas.Admin.Models.PermissionsModel", "Permission")
                        .WithMany("PermissionRole")
                        .HasForeignKey("Permission_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebsiteBanHang.Areas.Admin.Models.RoleModel", "Role")
                        .WithMany("PermissionRole")
                        .HasForeignKey("Role_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("WebsiteBanHang.Areas.Admin.Models.ProductModel", b =>
                {
                    b.HasOne("WebsiteBanHang.Areas.Admin.Models.BrandModel", "Brand")
                        .WithMany("Prodcut")
                        .HasForeignKey("HangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebsiteBanHang.Areas.Admin.Models.CategoryModel", "Category")
                        .WithMany("Prodcut")
                        .HasForeignKey("LoaiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("WebsiteBanHang.Areas.Admin.Models.UserRoleModel", b =>
                {
                    b.HasOne("WebsiteBanHang.Areas.Admin.Models.RoleModel", "Role")
                        .WithMany("UserRole")
                        .HasForeignKey("Role_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebsiteBanHang.Areas.Admin.Models.UserModel", "User")
                        .WithMany("UserRole")
                        .HasForeignKey("User_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebsiteBanHang.Areas.Admin.Models.Users_Details", b =>
                {
                    b.HasOne("WebsiteBanHang.Areas.Admin.Models.UserModel", "User")
                        .WithOne("userDetail")
                        .HasForeignKey("WebsiteBanHang.Areas.Admin.Models.Users_Details", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebsiteBanHang.Areas.Admin.Models.BrandModel", b =>
                {
                    b.Navigation("Prodcut");
                });

            modelBuilder.Entity("WebsiteBanHang.Areas.Admin.Models.CategoryModel", b =>
                {
                    b.Navigation("Prodcut");
                });

            modelBuilder.Entity("WebsiteBanHang.Areas.Admin.Models.PermissionsModel", b =>
                {
                    b.Navigation("PermissionRole");
                });

            modelBuilder.Entity("WebsiteBanHang.Areas.Admin.Models.RoleModel", b =>
                {
                    b.Navigation("PermissionRole");

                    b.Navigation("UserRole");
                });

            modelBuilder.Entity("WebsiteBanHang.Areas.Admin.Models.UserModel", b =>
                {
                    b.Navigation("UserRole");

                    b.Navigation("userDetail");
                });
#pragma warning restore 612, 618
        }
    }
}
